env:
  es6: true
  node: true
extends: 
  - google
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - warn
    - ignoreStrings: true
      ignoreComments: true
plugins:
  - html

